// One-time data fetch: NCES School Attendance Boundary Survey (SABS) 2015-16.
// Pulls per-school attendance polygons for the East Bay districts we map OUTSIDE
// Oakland (OUSD has its own live 2025-26 boundaries via script/fetch-ousd.mjs)
// and writes a compact bundled TS the SchoolMap component imports. SABS is
// frozen (the survey was discontinued), so we bundle it rather than fetch live.
//
// Run: node script/fetch-sabs.mjs
//
// Source: https://nces.ed.gov/programs/edge/SABS  (level 1=elem, 2=middle, 3=high, 4=other 6-12)

import { writeFile, mkdir } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, "..", "client", "src", "data", "sabsAttendance.ts");

// Target districts (NCES leaid) — the non-Oakland districts we map.
const LEAIDS = {
  "0604740": "Berkeley Unified",
  "0601770": "Alameda City Unified",
  "0630330": "Piedmont City Unified",
  "0601860": "Albany City Unified",
  "0641250": "Walnut Creek Elementary",
  "0620310": "Lafayette Elementary",
  "0628860": "Orinda Union Elementary",
  "0625740": "Moraga Elementary",
  "0601650": "Acalanes Union High",
  "0634680": "San Leandro Unified",
  "0632550": "West Contra Costa Unified", // big district — filtered to El Cerrito/Kensington below
};

// WCCUSD spans Richmond → Hercules; keep only the El Cerrito/Kensington schools we map.
const WCCUSD_ID = "0632550";
const WCCUSD_KEEP = new Set([
  "Kensington Elementary", "Madera Elementary", "Harding Elementary",
  "Fairmont Elementary", "Fred T. Korematsu Middle", "El Cerrito High",
]);

const ENDPOINT =
  "https://nces.ed.gov/opengis/rest/services/K12_School_Locations/SABS_1516/MapServer/0/query";

function round(n) {
  return Math.round(n * 1e5) / 1e5; // ~1m precision, keeps the file small
}

// GeoJSON geometry -> array of rings, each a list of [lng, lat] (rounded).
function geometryToRings(geom) {
  if (!geom) return [];
  const rings = geom.type === "Polygon" ? geom.coordinates
    : geom.type === "MultiPolygon" ? geom.coordinates.flat()
    : [];
  return rings.map(ring => ring.map(([lng, lat]) => [round(lng), round(lat)]));
}

async function main() {
  const leaList = Object.keys(LEAIDS).map(id => `'${id}'`).join(",");
  const params = new URLSearchParams({
    where: `leaid IN (${leaList}) AND schnam<>'Unassigned' AND level IN ('1','2','3','4')`,
    outFields: "schnam,level,leaid",
    f: "geojson",
    outSR: "4326",
    maxAllowableOffset: "0.0002", // server-side generalization (~22m)
  });
  const url = `${ENDPOINT}?${params.toString()}`;
  console.log("Fetching SABS attendance boundaries…");
  const res = await fetch(url);
  if (!res.ok) throw new Error(`SABS request failed: HTTP ${res.status}`);
  const geo = await res.json();
  const feats = geo.features || [];
  if (!feats.length) throw new Error("SABS returned 0 features — check leaids/endpoint");

  const out = feats
    .filter(f => f.properties.leaid !== WCCUSD_ID || WCCUSD_KEEP.has(f.properties.schnam))
    .map(f => ({
      name: f.properties.schnam,
      level: f.properties.level, // "1" elem, "2" middle, "3" high, "4" other 6-12
      district: LEAIDS[f.properties.leaid] || f.properties.leaid,
      rings: geometryToRings(f.geometry),
    }))
    .filter(s => s.rings.length > 0);

  await mkdir(path.dirname(OUT), { recursive: true });
  const header =
    "// AUTO-GENERATED by script/fetch-sabs.mjs — do not edit by hand.\n" +
    "// NCES School Attendance Boundary Survey (SABS) 2015-16, non-Oakland East Bay districts.\n" +
    "// level: \"1\" elementary, \"2\" middle, \"3\" high, \"4\" other (6-12). rings: [ [ [lng,lat], ... ], ... ]\n" +
    "export type SabsZone = { name: string; level: string; district: string; rings: number[][][] };\n\n" +
    "export const sabsAttendance: SabsZone[] = ";
  await writeFile(OUT, header + JSON.stringify(out) + ";\n");

  const byLevel = out.reduce((m, s) => ((m[s.level] = (m[s.level] || 0) + 1), m), {});
  const byDist = out.reduce((m, s) => ((m[s.district] = (m[s.district] || 0) + 1), m), {});
  const kb = (JSON.stringify(out).length / 1024).toFixed(0);
  console.log(`Wrote ${out.length} zones (${kb} kB) to ${path.relative(process.cwd(), OUT)}`);
  console.log("By level:", byLevel, "(1=elem 2=middle 3=high 4=other6-12)");
  console.log("By district:", byDist);
}

main().catch(e => { console.error(e); process.exit(1); });
